### PR TITLE
add comma for multi-value fields

### PR DESCRIPTION
**Pull request by nate-rcl**
**JIRA Ticket**: (link)

https://jira.duraspace.org/browse/ISLANDORA-1914

* Other Relevant Links (Google Groups discussion, related pull requests, Release pull requests, etc.)

# What does this Pull Request do?

Fixes issue where Solr search results that use a multi-field property and are linked are not properly separated - for example multiple title fields.

A brief description of what the intended result of the PR will be and/or what problem it solves.

Adds a comma separator between each value.

# What's new?

Changes the displayed text so that a comma separator is added between each field

# How should this be tested?

* Set up Islandora to use Solr search
* Add the metadata field as one of the fields to be displayed on search 
* Create metadata record with multiple titles
* Set the field to link back to the object
* Search for record with multiple titles
* Ensure that both titles are displayed and a comma separator is used to separate both fields

@Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by DiegoPino** [comment]
Hey @nate-rcl. Not sure if this can be seen as a bug, but for sure it is something that needs improvement. I wonder if it would not be a better approach to re-use `islandora_solr_search_field_value_separator` => [see implementation details](https://github.com/Islandora/islandora_solr_search/search?utf8=✓&q=islandora_solr_search_field_value_separator)  
, variable that  already exists to separate truncated multi values instead of fixing it to a `","`, which could maybe not be the general use case  or could make other more weird but valid use case impossible? 
This would require of course some rewording of the definition of that variable (mostly changing or adding to the description in the form that sets it). How do feel about that?

Pinging @nhart here also as maintainer and @MorganDawe as Solr search enthusiasts 😄

**Comment by nate-rcl** [comment]
@DiegoPino we considered it a bug because our users were seeing titles that looked like the following in the Solr search results: "Nebraska Seedling PlumThompson's Gold Plum" when it should be separated like the following "Nebraska Seedling Plum, Thompson's Gold Plum".   

Using the generic separator with a default setting that sounds like a good way to do it. We used a comma based on the recommendation from our cataloging department which looks like it is the default.

**Comment by nhart** [comment]
I agree with @DiegoPino, it should be using the islandora_solr_search_field_value_separator var and a fall back to '' as to not break current implementations.
I think the current wording is fine and that this PR is correcting something that was missed on initial PR https://github.com/Islandora/islandora_solr_search/pull/302

**Comment by DiegoPino** [comment]
Hi, thanks @nate-rcl and @nhart! Looks pretty good. So just to be sure, is the wording here fine?
https://github.com/Islandora/islandora_solr_search/blob/7149d60c486d0b155e9da5c8f6f39fc283069bb8/includes/admin.inc#L411-L422.
And is that the $separator we are using? 

Just checking, before approving.

Thanks to both

**Comment by nate-rcl** [comment]
@DiegoPino looks good to me. Would you like me to issue a new pull request or are you all set with the change?

**Review by DiegoPino — APPROVED** [review]
@whikloj says its fine. He is always right 😄

**Pull request merged**
