### PR TITLE
Fix enclosure url error when used in conjunction with @rosiel's islandor...

### PR DESCRIPTION
**Pull request by ruebot**
...a_pathauto

I noticed that when using @rosiel's islandora_pathauto in conjunction with this, the way the $enclosure_url was being declared previously just added on to the rewritten url, resulting in a 404 to the dsid. This solution should guarantee hitting the dsid.

### CODE REVIEW

**Comment by rosiel** [comment]
Nick do you have sub-pathauto module installed? I have it set to alias paths 3 deep. Of course, if doing this causes a noticeable decrease in performance, as they warn you about, then your fix would be a much better solution!

**Comment by rosiel** [comment]
Yes it does. I think I'll make it a requirement for islandora_pathauto.

**Comment by rosiel** [comment]
Ooh, no I don't. That'll be interesting to see. Thanks Nick!

**Comment by jonathangreen** [comment]
@ruebot I would guess this is your problem:
https://github.com/Islandora/islandora_jwplayer/blob/7.x/islandora_jwplayer.module#L46

We send URLs to jwplayer in the form:
islandora/objects/{pid}/datastreams/{MKV}/fake_filename.mkv 

because JWPlayer implies the mimetype from the extension and with our normal urls, appending anything to the end of them just gets you the same file. Perhaps pathauto isn't doing that.

**Comment by jonathangreen** [comment]
We also do this with the PDF solution pack download links: 
islandora/objects/{pid}/datastreams/PDF/file.pdf

So that older browsers (cough... IE) download the files correctly.

**Pull request closed without merging**
