### PR TITLE
Addition of highlighting the search term in the results. Moved over from...

### PR DESCRIPTION
**Pull request by jordandukart**
... Colorado's custom Solr.

### CODE REVIEW

**Comment by DannyJoris** [comment]
Hi Jordan, why did you add the sorting snippet? Populating the sort parameter happens around line 115 of IslandoraSolrQueryProcessor.inc, regardless of dismax use.

**Comment by DannyJoris** [comment]
Thanks for your pull requests, btw. :)

**Comment by jordandukart** [comment]
Colorado moved directly to core version of islandora_solr_search. Myself and Nelson noticed that when we passed a sort=date_s asc or desc through the url (to set up the RSS feeds), the sort parameter was not being grabbed. 

I'll ping/see you tomorrow so we can discuss this in more detail.

**Comment by jordandukart** [comment]
Talked to Danny and reverted the sort change out of my local branch. A fix for sorting is present in one of Danny's branches that will be moved into core eventually.

**Pull request merged**
