### PR TITLE
Release pull: Improve default query sort string helptext

### PR DESCRIPTION
**Pull request by bondjimbond**
Release pull for #337 

# Interested parties
@DiegoPino @rosiel

### CODE REVIEW

**Comment by DiegoPino** [comment]
@bondjimbond, tiny note: what is that extra commit at the beginning? https://github.com/Islandora/islandora_solr_search/pull/340/commits/e00e66fe3453a8dc9f7485625d1ff153f0549e35? Could you rebase this pull so that one does not carry over? It does not change anything in the code but troubles/confuses workflow and git history. I could squash and merge to obscure, still, will add Adam as a contributor in a strange way.

**Comment by bondjimbond** [comment]
@DiegoPino I... don't know? I am using the same base as in #337. This kind of thing is mysterious to me. 

How does one rebase?

**Comment by DiegoPino** [comment]
@bondjimbond yeah, 7.x and 7.x-1.11 are different by now, both branches have diverged already, means you need to sync this one from here and then apply the change manually probably (sounds like alchemy i know!).
 Do to so you can first rollback a bit your local branch (via `git reset hashofrollback` see git log to find the hashofrollback) then sync from here (upstream), then apply and then git push --force your bondjimbond:improve_helptext to your fork. 

https://help.github.com/articles/about-git-rebase/

Hope that helps

**Comment by bondjimbond** [comment]
I read that over... honestly, much went over my head. Would squash-and-merge be acceptable instead? I think understanding the process of rebasing etc would take more time/work than it's worth at this moment.

**Comment by DiegoPino** [comment]
Yep, can do: https://blog.github.com/2016-04-01-squash-your-commits/#enter-commit-squashing
No worries, next time.

**Pull request merged**
