### PR TITLE
6.x

### PR DESCRIPTION
**Pull request by DannyJoris**
- added a display switch block
- changed the way displays are set in the url. Instead of ?display=foo it's in islandora/solr/search/query/-/dismax/foo
- merged Alan's changes
- cleaning up

### CODE REVIEW

**Comment by bwoodhead** [comment]
Hey Danny, 

This changes the interface to a few function calls. I will need to check with Jon, Paul and Alan to make sure it's ok.

Ben

**Comment by DannyJoris** [comment]
Added a batch of coder review cleanups.

**Comment by DannyJoris** [comment]
That should be it for now :)

**Comment by DannyJoris** [comment]
<del>Alan and I should review the issue in the last commit soon.</del> Tabledrag did work - see next commit.

**Comment by DannyJoris** [comment]
Added tabledrag again. It was working fine after all. It was the uksort() that was confusing me so I removed that. uksort() sorted the display profiles alphabetically but always put the default display first. This was nice before, but now that we can set weight to the displays, this got very confusing.

**Pull request merged**
