### PR TITLE
GUI-configurable simple search fields

### PR DESCRIPTION
**Pull request by adam-vessey**
**Jira:** https://jira.duraspace.org/browse/ISLANDORA-1530
# What does this Pull Request do?

Allow the GUI-configured `Query fields` (`qf`; the fields for dismax/simple search) to be preferred over those defined in the selected request handler.
# How should this be tested?
1. When not checked (default, matches current functionality):
   1. With `qf` in the request handler, the fields in the `Query fields` textarea should _not_ be used.
   2. Without `qf` in the request handler, the fields in the `Query fields` textarea should be used.
2. When checked:
   1. The fields in the `Query fields` textarea should be used, independent of `qf` existing in the selected request handler.
# Screenshots
## Before Screenshot

Before Screenshot
## After Screenshot

After Screenshot
# Additional Notes:
- **Does this change require documentation to be updated?** Unsure: There does not appear to be a mention of "Query fields" in either
  - https://wiki.duraspace.org/display/ISLANDORA/Islandora+Solr+Settings or
  - https://wiki.duraspace.org/pages/viewpage.action?pageId=69833573#Search&DiscoveryinIslandora-7.SetQueryDefaults
  
  and a quick search on the wiki did not turn up any other probabilities. 
- **Could this change impact execution of existing code?** Unlikely; though, possible if one were depending on the absence of the `qf` in the `IslandoraSolrQueryProcessor::$solrParams` when `qf` is defined in the request handler. As this case already depends on external configuration (Solr's request handler) we should consider such code to be in fault.

**Tagging:** @jordandukart (component manager)

---

Adam Vessey
_Developer_
**[discoverygarden inc.](http://www.discoverygarden.ca) | Managing Digital Content**

### CODE REVIEW

**Comment by jordandukart** [comment]
As the component management I have reviewed and tested this. Can another committer verify before merging?

**tagging:** @mjordan @ruebot @DiegoPino @whikloj @rosiel 

---

Jordan Dukart
_Developer_
**[discoverygarden inc.](http://www.discoverygarden.ca) | Managing Digital Content**

**Comment by whikloj** [comment]
Love this change, as there is not great documentation that we currently use the fields defined in the solr_config.xml.
I'll have a quick test and let you know.

**Comment by whikloj** [comment]
Reviewed and tested. Looks good to me. :+1:

**Comment by jordandukart** [comment]
Thanks @whikloj, will merge :smile:!

**Comment by willtp87** [comment]
@ruebot

Thanks, spreading that tag around the office now.

---

William Panting
_Developer_
_[discoverygarden inc.](http://www.discoverygarden.ca) | Managing Digital Content_

**Pull request merged**
