### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by librarychik**
**JIRA Ticket**: (link)
- Other Relevant Links (Google Groups discussion, related pull requests, Release pull requests, etc.)
# What does this Pull Request do?

A brief description of what the intended result of the PR will be and/or what problem it solves.
# What's new?

A in-depth description of the changes made by this PR. Technical details and possible side effects.

Example:
- Changes x feature to such that y
- Added x
- Removed y
# How should this be tested?

A description of what steps someone could take to:
- Reproduce the problem you are fixing (if applicable)
- Test that the Pull Request does what is intended.
- Please be as detailed as possible.
- Good testing instructions help get your PR completed faster.
# Additional Notes:

Any additional information that you think would be helpful when reviewing this PR.

Example:
- Does this change require documentation to be updated? 
- Does this change add any new dependencies? 
- Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? 
- Could this change impact execution of existing code?
# Interested parties

Tag (@ mention) interested parties or, if unsure, @Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by manez** [comment]
First commit, yay @librarychik !

Just a note for next time - there's a pile of template text that we have pre-loaded for pull requests. You can delete what isn't relevant and write over what is :smile:

**Comment by manez** [comment]
This is correcting a discrepancy between the README (Apache Solr 1.4) and the page on the [Confluence Wiki](https://wiki.duraspace.org/display/ISLANDORA/Islandora+Solr+Search) (Apache Solr 4.2)i. @diego or @jordandukart, as Maintainers can you confirm which page has it right?

**Comment by mjordan** [comment]
Yes, congrats @librarychik !

**Comment by manez** [comment]
!! 

They do not and she does not yet. Thanks for the reminder :sweat: 

@librarychik , if you'd be so kind, I will need a signed iCLA to merge this commit: http://islandora.ca/sites/default/files/islandora_cla.pdf

**Comment by mjordan** [comment]
It's about time SFU got a cCLA in place. I'll start that.

**Comment by mjordan** [comment]
You will owe me a beer, my friend.

**Comment by librarychik** [comment]
Wow you guys are quick.  I'm on it, will get the CLA filled out :)

**Comment by manez** [comment]
CLA now on file! 

https://github.com/Islandora/islandora/wiki/Contributor-License-Agreements

**Comment by manez** [comment]
Got confirmation that 4.2 is the right one, so... in goes @librarychik 's first PR!

@librarychik can you do another PR on the release branch? Ping me if you need any guidance :smile:

**Pull request merged**
