### PR TITLE
Update screenshot and wording in README

### PR DESCRIPTION
**Pull request by bencomp**
**JIRA Ticket**: n/a

This is part of the documentation effort for 7.x-1.11. See also #338 

# What does this Pull Request do?

I updated the screenshot for the basic Solr settings and included both screenshots in the repository, following GitHub guidelines for READMEs. I also changed some sentences to make them clearer.

# What's new?

* screenshots are now included in `docs/`
* the description paragraph starts with the module's full name
* the link to the PHP note on dates has a better label and goes to the secure webpage
* the answer on PID search explains how to escape the colon

# How should this be tested?

Read the changes, please.

# Additional Notes:
none

# Interested parties
@whikloj and @Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by DiegoPino** [comment]
@bencomp only issue I see is the deletion of https://wiki.duraspace.org/display/ISLANDORA/Islandora+Solr+Search (not the link here, that is ok, but the real page) because a lot of googly things are pointing to it, and older docs too, well, that is not that terrible because the version specific copy still exists. I would suggest we discuss this with @rosiel and @dannylamb, maybe keep both, maybe duraspace has redirect option or maybe it is just fine and it needed to go. Thoughts @Islandora/7-x-1-x-committers?

**Comment by DiegoPino** [comment]
I will merge later today (pull is good!) once i get an answer on how to proceed with the WIKI.

**Comment by rosiel** [comment]
I think it's fine. As you said, the old pages exist. There is no automatic redirect for externally saved links to confluence pages, but there is a plugin that can (hopefully) do it. Under "Page information" there is a list of "incoming links" that lists other sites that point to a page - but as far as I can tell Diego fixed them yesterday. (I can't see what points to Islandora+Solr+Search without re-enabling it, so I didn't). 

https://wiki.duraspace.org/pages/viewinfo.action?pageId=69833534

**Comment by DiegoPino** [comment]
Merging. Thanks @bencomp !

**Pull request merged**
