### PR TITLE
Updates for grid display

### PR DESCRIPTION
**Pull request by t4k**
Running the grid display results through the utility functions and updating the template allows it to use the fields defined in Default display settings under Solr settings.

### CODE REVIEW

**Comment by willtp87** [comment]
If I understand this correctly, this will expand the information displayed for this view.  The stripped down display was very explicitly the original requirements here and this change would likely displease some users.  I suggest a new display be created; perhaps 'Detailed Grid'.

**Comment by t4k** [comment]
Thanks for the info about the original requirements. I didn't know about that.

The way I implemented this gives the _option_ to expand the information displayed for the grid view. It would look exactly the same as it did before if the title field alone was added without a label in the **Display fields** section.

My motivations: When I first started using the Grid view, I was very confused as to why it didn't respect the field settings that seemed to be allowed. At the very least, there should be some help text explaining which displays use those settings and which don't. I did not address that here, though.

**Comment by t4k** [comment]
Sure, what do I need to do for it? I have a JIRA account now, but I don't know the procedure for filing issues, etc. TommyK is my username there.

**Comment by adam-vessey** [comment]
I'm... still not sure about this... The list of fields isn't configurable per display, so having just the grid view with labels vs having full list/tables views will not be possible with this change (I mean, you can change between the displays through the UI)... As per @willtp87's comment, I could see making a copy of the display to populate with more detailed info, but the original grid should probably be kept as-is.

**Comment by willtp87** [comment]
I think we have consensus, can we close this pull?

**Pull request closed without merging**
