### PR TITLE
remove include as it is not needed

### PR DESCRIPTION
**Pull request by nhart**
addition to https://github.com/Islandora/islandora_solr_search/pull/296

### CODE REVIEW

**Review by whikloj — APPROVED** [review]
Tested, works... will give it an hour then merge.

**Comment by DiegoPino** [comment]
__

**Comment by DiegoPino** [comment]
@whikloj sorry closed..open again. My touchpad went crazy 😢

**Comment by whikloj** [comment]
@DiegoPino was there an issue? Or were you just giving a thumbs up?

**Comment by DiegoPino** [comment]
@whikloj no worries, sorry. UI error.

**Comment by nhart** [comment]
thanks @whikloj

**Pull request merged**
