### PR TITLE
ISLANDORA-1573: Provide port based on scheme if not given in URL

### PR DESCRIPTION
**Pull request by dltj**
Fixes ISLANDORA-1573

Ping: @jordandukart, module maintainer

### CODE REVIEW

**Comment by jordandukart** [comment]
Would need something identical at least here: https://github.com/Islandora/islandora_solr_search/blob/7.x/includes/query_processor.inc#L322 and anywhere else `Apache_Solr_Service` is called directly. Similarly any custom modules that may instantiate `Apache_Solr_Service` directly would have to account for this too. Right off the bat the entities solution pack and facet pages are doing this. If this route is undertook some additional documentation would properly be benificial as to this default behavior.

**Comment by dltj** [comment]
Hmmm -- then there seem to be other issues because the line you mention doesn't include a call to `islandora_solr_check_http()` as [the function I originally modified does](https://github.com/dltj/islandora_solr_search/blob/fd4d454a4ae52d0ee071cbff97416287364835b2/includes/luke.inc#L20).  Arguably, the check for whether the port number is included could go into `islandora_solr_check_http()`, then have an audit of modules that use `Apache_Solr_Service` to make sure that function is called first?

**Comment by whikloj** [comment]
Instead of changing all the calls to Apache_Solr_Service to use `islandora_solr_check_http()`. Would it be acceptable to make your function a small utility function that accepts and returns the results of the `parse_url()` call. 

```
function islandora_solr_validate_port(array $parsed_url) {
  // If the port isn't specified, provide the defaults
  if ((!isset($parsed_url['port'])) && (isset($parsed_url['scheme']))) {
    if ($parsed_url['scheme'] == 'http') {
      $parsed_url['port'] = 80;
    } else if ($parsed_url['scheme'] == 'https') {
      $parsed_url['port'] = 443;
    }
  }
  return $parsed_url;
}
```

Then we can drop it in as a replacement for places like @jordandukart mentioned ala

```
$path_parts = islandora_solr_validate_port(parse_url(variable_get('islandora_solr_url', 'localhost:8080/solr')));
$solr = new Apache_Solr_Service($path_parts['host'], $path_parts['port'], $path_parts['path'] . '/');
```

Then updating documentation people with external uses (like me), can make the same change as above to my URL parsing.

**Comment by dltj** [comment]
That makes sense to me, but I wonder about the other things happening in `islandora_filter_ping()` that may not be happening elsewhere:

```
  // Check that scheme specifier is present.
  $solr_url = islandora_solr_check_http($solr_url);
  // Check for valid URL string.
  if (!filter_var($solr_url, FILTER_VALIDATE_URL)) {
    return FALSE;
  }
```

The proposed `islandora_solr_validate_port()` can accommodate the `$url = 'http://' . $url` part (if necessary, of course).  In which case it might make sense to call the new function `islandora_solr_parse_url_wrap()`.  But if we're going to go that far maybe it makes sense to abstract out the variable_get part, too:

```
function islandora_solr_url_path_parts($url = False) {
  if ($url === False) {
    $url = variable_get('islandora_solr_url', 'localhost:8080/solr');
  }

  $parsed_url = parse_url($url);
  if ($parsed_url === False) {
    return False;
  }

  // If the scheme isn't specified, assume 'http'
 if (!isset($parsed_url['scheme']) {
    $parsed_url['scheme'] = 'http';
  }

  // If the port isn't specified, provide the defaults.
  if ((!isset($parsed_url['port'])) && (isset($parsed_url['scheme']))) {
    if ($parsed_url['scheme'] == 'http') {
      $parsed_url['port'] = 80;
    } else if ($parsed_url['scheme'] == 'https') {
      $parsed_url['port'] = 443;
    }
  }

  return $parsed_url;
}
```

Damn -- I might have just talked myself into a significant amount of work.

**Comment by jordandukart** [comment]
@dltj, are you actively working on this or can this be closed?

**Comment by dltj** [comment]
Hey, @jordandukart -- I haven't been actively working on this, but the underlying problem is still there.  The fingers are willing to put in the time, but the number of hours in the day haven't been enough to get traction on it.  I haven't given up yet.

**Comment by DiegoPino** [comment]
@dltj any updates on this? just to keep the ball rolling?

**Comment by whikloj** [comment]
@dltj any updates?

**Comment by DiegoPino** [comment]
@whikloj I have not seen any response since September last year.Any thoughts? Do we keep open?

**Comment by whikloj** [comment]
@DiegoPino I don't mind leaving it open. Doesn't cause me any pain on a daily basis 😄

**Comment by DiegoPino** [comment]
+1 to no pain

**Pull request closed without merging**
