### PR TITLE
release pull for ISLANDORA-2327

### PR DESCRIPTION
**Pull request by nhart**
See https://github.com/Islandora/islandora_solr_search/pull/348 for details

### CODE REVIEW

**Comment by bondjimbond** [comment]
> sites/all/modules/islandora_solr_search/islandora_solr.module:
> +632: [minor] Files must end in a single new line character

Why is this happening on the release pull but not #348?

**Comment by DiegoPino** [comment]
@bondjimbond @nhart because this pull is different to #348. That one adds +12 lines, this +13 lines...

**Review by DiegoPino — CHANGES_REQUESTED** [review]
Please remove that extra line. thanks

**Review by DiegoPino — APPROVED** [review]
all good now!

**Pull request merged**
