### PR TITLE
check if pid is in the returned fields before trying to use it

### PR DESCRIPTION
**Pull request by nhart**

### CODE REVIEW

**Comment by jonathangreen** [comment]
Should we maybe put some warnings in the watchdog or something if the PID isn't there? Where was this coming up? 

Also how did this get committed by Kris?

**Comment by nhart** [comment]
The islandora downloadable vm has kris's username and email setup in git. I pushed my changes before realizing.

If you don't have the PID field specified in the list of fields to return and you have "Limit results to fields listed above?" checked, drupal throws a red wall of errors when using the fields display profile. I can create a JIRA ticket is you like.

**Comment by jonathangreen** [comment]
So in this case would it just not display any search results?

**Comment by nhart** [comment]
It displays whatever other fields specified, It just won't build a fedora item object and try get the TN when there's no PID field in the returned solr doc.

**Pull request merged**
