### PR TITLE
Address ISLANDORA-401 with some documentation changes

### PR DESCRIPTION
**Pull request by manez**
**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-401 with bonus change to acknowledge that https://jira.duraspace.org/browse/ISLANDORA-646 has been closed

# What does this Pull Request do?

Updates the documentation to add a new Q&A to the FAQ and update an old one. Brings things in line with the [wiki](https://wiki.duraspace.org/display/ISLANDORA/Islandora+Solr). Addresses literally the *OLDEST* open ticket in our JIRA.

# What's new?
One extra Q&A about Solr searches, escaped characters, and how Drupal's block visibility settings don't play nice. One change to an old Q&A to acknowledge that we Closed+Won't Fix the referenced issue. 

# How should this be tested?

Verify that the new Q&A is an adequate explanation of the issues raised by https://jira.duraspace.org/browse/ISLANDORA-401

# Additional Notes:
Any additional information that you think would be helpful when reviewing this PR.

Example:
* Does this change require documentation to be updated?  This change *is* documentation
* Does this change add any new dependencies? Nope
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? Nope
* Could this change impact execution of existing code? Nope

# Interested parties
Just a documentation update, so any @Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by DonRichards** [comment]
I don't know if this was already mentioned but they have updated that client from what I can see. 

The code points to Google code, the site says the following

--------------------------------
Apache Solr PHP Client
THIS PROJECT WAS MOVED TO GITHUB
https://github.com/PTCInc/solr-php-client
--------------------------------

Last update message to the Service.php was "Allows HTTPS connections to the Solr instance."
https://github.com/PTCInc/solr-php-client/commit/ecc04b532c60c81ff6d588948d016020452aaa0d

**Comment by DonRichards** [comment]
@manez My intention wasn't to stall this, I was wondering if anyone else was aware of this? It seemed relative.

**Comment by manez** [comment]
I'm honestly not sure @DonRichards . Fixing docs is in my wheelhouse, but evaluating the underlying bug is not 😓

**Comment by rosiel** [comment]
I thought the point was that we're using a vendored (forked version) of the php solr client, and while un-doing our customizations to move to using the Official PHP solr client is a laudable goal (because it can do HTTPs and other things), nobody's willing to take on that quest.

**Comment by DonRichards** [comment]
It does sound like something that should be done.

**Comment by manez** [comment]
Unfortunately, @DonRichards I think that unless you're volunteering to take it on (which would be 🎉 for sure!), we're back in the same holding pattern that the ticket has held since 2012, which it how it ended up closed.

**Review by rosiel — APPROVED** [review]

**Review by whikloj — APPROVED** [review]

**Comment by whikloj** [comment]
@rosiel not trying to steal your merge. So if you'd like to, please do. 🙇

**Pull request merged**
