### PR TITLE
7.x islandora 1852

### PR DESCRIPTION
**Pull request by nhart**
**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1852

# What does this Pull Request do?
Adds a block to allow the user to change the page size of search results.

# What's new?
A new block to place.

# How should this be tested?
See Jira ticket for steps to test.

# Additional Notes:
* Does this change require documentation to be updated? no
* Does this change add any new dependencies? no
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? no
* Could this change impact execution of existing code? no

# Interested parties
@Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by whikloj** [comment]
@nhart not sure I understand this one. But if I'm right, this gives you a block with alternative options for the number of search results to return?

So like default might be **20** and limits might be **20,50,100** so the block gives you
- 20
- [50]()
- [100]()

yes?

**Comment by nhart** [comment]
@whikloj  correct

**Comment by whikloj** [comment]
@nhart I hit a small problem, if you start paging through and then change the results limit the current page is maintained. 
This caused a problem when I was on page 3 using 20 item results with a total of 76 results and pressed the **100** limit link. Perhaps it should reset the current page when you use this?

Apache error log reports:

```
[Wed Nov 16 21:40:37.575047 2016] [:error] [pid 12821] [client 10.0.2.2:56186] PHP Fatal error:  Call to undefined function islandora_is_valid_pid() in /islandora_modules/islandora_solr_search/includes/results.inc on line 942, referer: http://localhost:8000/islandora/search/model?page=2&type=dismax&limit=20
```

**Review by whikloj — APPROVED** [review]
I'm good, I'll leave this up for a bit in case anyone has issues. If not I'll merge

**Comment by DiegoPino** [comment]
@whikloj @nhart ++ from me.

**Comment by willtp87** [comment]
I think this will need an added check like https://github.com/Islandora/islandora_solr_search/blob/7.x/includes/blocks.inc#L839 to avoid showing up where it is not useful.

**Review by whikloj — APPROVED** [review]
Tested with new changes, still works and now disappears on non-search result pages. Good catch @willtp87.

**Pull request merged**
