### PR TITLE
sortable collections when using solr query backend

### PR DESCRIPTION
**Pull request by qadan**
**Jira:** https://jira.duraspace.org/browse/ISLANDORA-1588
# What does this Pull Request do?

This adds Solr sorting natively into the collection view when using the Solr query backend, both with a global sort and with sorting per-collection.

The reasons why this would be nice to have are detailed in the Jira ticket above.
# How should this be tested?

The `islandora_solr_search` module should be updated, and the Drupal database update hooks should be run to add the new sort string table to the database.

A new variable has been added, `islandora_solr_collection_sort`, that acts as a global sort setting for collections.

When using the Solr query backend for collection display, collections should:
- default to sorting by the Solr base sort setting
- sort instead by the Solr collection sort if that exists

A second variable has been added, `islandora_solr_individual_collection_sorting`, that toggles the ability to store individual collection sort strings in the database. An individual collection sort string, if found, takes precedence over the above two sort strings.
# Background context:

Most of this is addressed in the Jira ticket above, but the gist is this: the sort method for searching and the sort method for collection display most likely shouldn't be the same. In fact, the sort field used per-collection may not even be the same, because different collections may use different types of metadata. This will allow us to differentiate between these two things.
# Additional Notes:
- **Does this change require documentation to be updated?** Yes, new configuration options have been added, plus an update hook is required to be run.
- **Does this change add any new dependencies?** No
- **Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)?** No; this should work fine without repository modifications. In addition, by default, behaviour for the Solr collection display backend should remain the same unless sort strings are modified.
- **Could this change impact execution of existing code?** This shouldn't touch existing code.

**Tagging:** @jordandukart as the maintainer of this thingy

---

Something or other Dan
_Developer_
**[discoverygarden inc.](http://www.discoverygarden.ca) | Managing Digital Content**

### CODE REVIEW

**Comment by DiegoPino** [comment]
Hi @qadan, could we have a pre check (like if the vars/settings are set) before hitting the db? Just thinking of the "not using a specific sort"  use case, to avoid some performance loss? or maybe (stop me if i'm say non-sense) cache per collection, not sure if accessing the cache is faster than your simple query anyway, so it's just an idea.

**Comment by qadan** [comment]
Hey @DiegoPino! Where would you be looking for this pre-check? As in, have a toggleable 'use individual collection sort strings' that defines whether or not we even do [this db_select](https://github.com/Islandora/islandora_solr_search/pull/261/files#diff-c16639862ca30d1256d58aa53b44c420R269)? That's certainly something I could do; would avoid having to hit the database altogether if per-collection sorting isn't wanted

**Comment by DiegoPino** [comment]
@qadan, that would be nice and enough! Thanks for responding so quick :smile:

**Comment by qadan** [comment]
Updated! And updated the description as well.

**Comment by DiegoPino** [comment]
@qadan, pretty good! Thanks.

**Comment by willtp87** [comment]
@qadan,

This is looking good. However I am unsure if the new configuration piece should be in the Solr or collection SP admin.
I think as part of the collection admin triggered by states on selecting Solr provides the best context.
Does anyone (perhaps the UIIG) have input?

Thanks!

---

William Panting
_Developer_
_[discoverygarden inc.](http://www.discoverygarden.ca) | Managing Digital Content_

**Comment by qadan** [comment]
I kind of leaned toward that initially, but went with the Solr admin page because it avoids a _form_alter and I felt like someone might think the collection query defaults belong in the Solr query defaults section. But I'm also really partial to hiding config options behind states to improve context. I'm happy to do whatever people feel like.

Dan Thing
_Developsman_
_[discoverygarden inc.](http://www.discoverygarden.ca) | Managing Digital Content_

**Comment by rosiel** [comment]
Discussed at the UIIG meeting today. We suggest that if possible, this config piece would make more sense in the Collection SP Admin.  We are also in support of hiding options behind states to improve context. 

DanOfManyThings++, this is a great improvement.

**Comment by qadan** [comment]
Done!
- Dan
- Thing

**Comment by willtp87** [comment]
@qadan,

I think this is good to go.

Thanks!

---

William Panting
_Developer_
_[discoverygarden inc.](http://www.discoverygarden.ca) | Managing Digital Content_

**Comment by DiegoPino** [comment]
@ruebot, @rosiel, @qadan, just a last minute question. If moving admin to Collection SP via hook, do we need to update the module's requirements (README, info) ? Or not needed?

**Comment by qadan** [comment]
The .info should be fine, as there's no strict dependency on islandora_basic_collection (all added functionality starts from implemented hooks).

I should add a blurb to the README though; the collection query backend isn't documented, and neither is the configuration.

**Comment by whikloj** [comment]
:+1: to the documentation

**Comment by DiegoPino** [comment]
Sounds fine. Once travis passes i'm also good for a merge. Thanks @qadan

**Comment by rosiel** [comment]
Looks great! Seeing a lot of go-aheads and no outstanding concerns, I'm gonna merge.

**Pull request merged**
