### PR TITLE
Update screenshots and some words in README

### PR DESCRIPTION
**Pull request by bencomp**
**JIRA Ticket**: n/a

This is part of the documentation effort for 7.x-1.11.

# What does this Pull Request do?

I updated the screenshot for the basic Solr settings and included both screenshots in the repository, following GitHub guidelines for READMEs. I also changed some sentences to make them clearer.

# What's new?

* screenshots are now included in `docs/`
* the description paragraph starts with the module's full name
* the link to the PHP note on dates has a better label and goes to the secure webpage
* the answer on PID search explains how to escape the colon

# How should this be tested?

Read the changes, please.

# Additional Notes:
none

# Interested parties
@whikloj and @Islandora/7-x-1-x-committers

### CODE REVIEW

**Review by DiegoPino — APPROVED** [review]
Great. @rosiel ping. We need to add some notes/discussion about this next releases. As discussed today in [IRC](http://irclogs.islandora.ca/2018-05-21.html) with @bencomp (he suggested this) adding images to /docs folder instead of relying on the internet is a better practice for README files. Thanks, @bencomp for bringing this up and showing us the light 😄

**Comment by DiegoPino** [comment]
Will wait 24 hours in case @whikloj wants to request changes and if not will merge. Thanks

**Comment by rosiel** [comment]
Hate to be this person, but the module name is "Islandora Solr". Its machine name is islandora_solr because that's what the .module and .info files use. https://github.com/Islandora/islandora_solr_search/blob/7.x/islandora_solr.info#L1 

The repository name on github, and the folder that you'll probably have it in, is islandora_solr_search.

**Comment by rosiel** [comment]
I love the new /docs folder for images. Thanks @bencomp!

**Comment by bencomp** [comment]
@rosiel thanks for clearing that up! I will fix that.

Maybe we can clear up the relations between the names, here in the code, but also on the Confluence wiki as the module is listed as [Islandora Solr Search](https://wiki.duraspace.org/display/ISLANDORA/Islandora+Solr+Search) over there.

**Comment by DiegoPino** [comment]
@bencomp following your suggestion: https://wiki.duraspace.org/pages/diffpagesbyversion.action?pageId=69833534&selectedPageVersions=12&selectedPageVersions=13
But i can not change the page URL/automatic title because there are too many internet links coming back to this one in the wild. Suggestions WIKI experts?

**Comment by bencomp** [comment]
@DonRichards (and @rosiel) should I update all "Islandora Solr Search" references in the readme to "Islandora Solr"?

@DiegoPino I can see that seven pages have the correct link, but the others should be updated manually. I found on one page that the link target was the full URL rather than a Confluence internal link.

**Comment by DiegoPino** [comment]
@bencomp feel free to update the reference in all places where you find it/can do it. But most urgent really is all for this release, especially if moving things forward with deprecating Duraspace wiki docs.  This pull just needs to be updated to address @rosiel's feedback to be merged. Let me know when done to do so. Thanks!

**Comment by rosiel** [comment]
Looks good, folks. Sorry to be "that person."

**Comment by DiegoPino** [comment]
@bencomp merged! Thanks for this =)

**Pull request merged**
